version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqlcontainer
    environment:
      MYSQL_ROOT_PASSWORD: Yulia2112
      MYSQL_DATABASE: game_market_db
    ports:
      - "3307:3306"
    networks:
      - networkmysql

  app:
    image: marketimage:latest
    container_name: marketcontainer
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: game_market_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Yulia2112
    ports:
      - "8090:8081"
    depends_on:
      - mysql
    networks:
      - networkmysql

networks:
  networkmysql:
    driver: bridge
