@startuml

entity Authorities {
    * id : BINARY(16)
    * authority : VARCHAR(255)
}

entity Carts {
    * id : BINARY(16)
    * price : DECIMAL(10,2)
}

entity Developers {
    * id : BINARY(16)
    * name : VARCHAR(255)
    * creation_date : DATE
}

entity Games {
    * id : BINARY(16)
    * name : VARCHAR(255)
    * overall_rating : DECIMAL(2,1)
    * price : DECIMAL(10,2)
    * sales : INT
    * developer_id : BINARY(16)
}

entity Promocodes {
    * id : BINARY(16)
    * type : VARCHAR(255)
    * code : VARCHAR(255)
    * discount : INT
    * quantity : INT
}

entity Roles {
    * id : BINARY(16)
    * name : VARCHAR(255)
}

entity UserInfo {
    * id : BINARY(16)
    * email : VARCHAR(255)
    * password : VARCHAR(255)
}

entity Users {
    * id : BINARY(16)
    * nickname : VARCHAR(255)
    * balance : DECIMAL(10,2)
    * user_info_id : BINARY(16)
    * cart_id : BINARY(16)
}

entity Reviews {
    * id : BINARY(16)
    * comment : TEXT
    * stars : VARCHAR(255)
    * game_id : BINARY(16)
    * user_id : BINARY(16)
}

entity Orders {
    * id : BINARY(16)
    * price : DECIMAL(10,2)
    * user_id : BINARY(16)
    * promocode_id : BINARY(16)
}

entity Genres {
    * id : BINARY(16)
    * name : VARCHAR(255)
}

entity CartsGames {
    * cart_id : BINARY(16)
    * game_id : BINARY(16)
}

entity OrdersGames {
    * order_id : BINARY(16)
    * game_id : BINARY(16)
}

entity PromocodesOrders {
    * promocode_id : BINARY(16)
    * order_id : BINARY(16)
}

entity RolesAuthorities {
    * role_id : BINARY(16)
    * authority_id : BINARY(16)
}

entity UsersFavoriteGames {
    * user_id : BINARY(16)
    * game_id : BINARY(16)
}

entity UsersReviews {
    * user_id : BINARY(16)
    * review_id : BINARY(16)
}

entity GameGenre {
    * game_id : BINARY(16)
    * genre_id : BINARY(16)
}

Users }|--|| UserInfo : has
Users }|--|| Carts : has
Reviews }|--|| Games : reviews
Reviews }|--|| Users : reviewed by
Games }|--|| Developers : developed by
CartsGames }|--|| Carts : part of
CartsGames }|--|| Games : contains
OrdersGames }|--|| Orders : part of
OrdersGames }|--|| Games : contains
PromocodesOrders }|--|| Promocodes : contains
PromocodesOrders }|--|| Orders : contains
RolesAuthorities }|--|| Roles : role
RolesAuthorities }|--|| Authorities : authority
UsersFavoriteGames }|--|| Users : likes
UsersFavoriteGames }|--|| Games : liked
UsersReviews }|--|| Users : reviews
UsersReviews }|--|| Reviews : reviewed
GameGenre }|--|| Games : has
GameGenre }|--|| Genres : belongs to

@enduml
