spring:
  main:
    banner-mode: off

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

#  sql:
#    init:
#      data-locations:
#        classpath:db/data.sql
#      schema-locations:
#        classpath:db/schema.sql
#      mode: always

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

server:
  port: 8081

logging:
  level:
    root: DEBUG