spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/game_market_db
    username: root
    password: Yulia2112

  sql:
    init:
      data-locations:
        classpath: db/data.sql
      schema-locations:
        classpath: db/schema.sql

